In [1]:
import numpy as np

In [2]:
arr = np.arange(11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [5]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [6]:
A= np.random.randn(10)

In [7]:
A


array([ 0.00880658,  0.90428054,  0.97012436,  1.20624035, -0.44038793,
       -1.08595232, -0.10970507, -1.47701671, -0.42081451, -0.05996476])

In [8]:
B= np.random.randn(10)

In [9]:
B

array([ 0.61004122,  0.86951687,  0.25013174,  1.07192635,  0.91721248,
       -1.28500828,  0.10968172, -0.40640562,  2.17904431, -1.25229427])

In [10]:
np.add(A, B)

array([  6.18847792e-01,   1.77379741e+00,   1.22025610e+00,
         2.27816670e+00,   4.76824556e-01,  -2.37096060e+00,
        -2.33552221e-05,  -1.88342233e+00,   1.75822980e+00,
        -1.31225903e+00])

In [11]:
np.maximum(A, B)

array([ 0.61004122,  0.90428054,  0.97012436,  1.20624035,  0.91721248,
       -1.08595232,  0.10968172, -0.40640562,  2.17904431, -0.05996476])

In [12]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"

In [13]:
import webbrowser
webbrowser.open(website)

True