In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [2]:
arr1= np.arange(9).reshape((3, 3))

In [3]:
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1, arr1], axis= 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
ser1= Series([0, 1, 2], index= ['T', 'U', 'V'])

In [9]:
ser1

T    0
U    1
V    2
dtype: int64

In [10]:
ser2= Series([3, 4], index= ['X', 'Y'])
ser2

X    3
Y    4
dtype: int64

In [11]:
pd.concat([ser1, ser2, ser1])

T    0
U    1
V    2
X    3
Y    4
T    0
U    1
V    2
dtype: int64

In [12]:
pd.concat([ser1, ser2], axis= 1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [13]:
pd.concat([ser1, ser2], keys= ['cat1', 'cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [14]:
pd.concat([ser1, ser2], keys= ['cat1', 'cat2'], axis= 1)

cat1  cat2
T   0.0   NaN
U   1.0   NaN
V   2.0   NaN
X   NaN   3.0
Y   NaN   4.0

In [15]:
dframe1 = DataFrame(np.random.randn(4,3), columns=['X', 'Y', 'Z'])
dframe1

X         Y         Z
0 -1.083574  0.141244 -0.993591
1  1.509948 -1.125563  1.066470
2  0.128330 -1.111823  0.223599
3  1.379206 -0.858685  0.211933

In [16]:
dframe2 = DataFrame(np.random.randn(3, 3), columns=['Y', 'Q', 'X'])
dframe2

Y         Q         X
0 -2.482338 -0.154437 -0.030913
1 -0.265682 -1.071834 -1.873885
2  0.011952  0.770047  0.253679

In [17]:
pd.concat([dframe1, dframe2])

Q         X         Y         Z
0       NaN -1.083574  0.141244 -0.993591
1       NaN  1.509948 -1.125563  1.066470
2       NaN  0.128330 -1.111823  0.223599
3       NaN  1.379206 -0.858685  0.211933
0 -0.154437 -0.030913 -2.482338       NaN
1 -1.071834 -1.873885 -0.265682       NaN
2  0.770047  0.253679  0.011952       NaN

In [18]:
pd.concat([dframe1, dframe2], ignore_index= True)

Q         X         Y         Z
0       NaN -1.083574  0.141244 -0.993591
1       NaN  1.509948 -1.125563  1.066470
2       NaN  0.128330 -1.111823  0.223599
3       NaN  1.379206 -0.858685  0.211933
4 -0.154437 -0.030913 -2.482338       NaN
5 -1.071834 -1.873885 -0.265682       NaN
6  0.770047  0.253679  0.011952       NaN

In [19]:
pd.concat([ser1, ser2], axis= 1, join_axes= [['U', 'V', 'Y']])

0    1
U  1.0  NaN
V  2.0  NaN
Y  NaN  4.0