In [9]:
import numpy as np

my_list1 = [1, 2, 3, 4]

my_array1 = np.array(my_list1)

In [10]:
my_array1

array([1, 2, 3, 4])

In [11]:
my_list2 = [11, 22, 33, 44]

my_lists = [my_list1, my_list2]

my_array2 = np.array(my_lists)
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [12]:
my_array2.shape

(2, 4)

In [13]:
my_array2.dtype

dtype('int64')

In [14]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [15]:
my_zeros_array = np.zeros(5)

In [17]:
my_zeros_array.dtype

dtype('float64')

In [18]:
np.ones((5, 5))

array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [19]:
np.empty(5)
np.empty((3, 4))

array([[ -2.31584178e+077,  -2.32034812e+077,   6.92754667e-310,
          1.06099790e-313],
       [  6.92754667e-310,   1.39077726e-309,  -2.31584178e+077,
         -2.31584178e+077],
       [  2.96439388e-323,   0.00000000e+000,   1.75871011e-310,
          3.50977866e+064]])

In [22]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [23]:
np.arange(5, 50, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37,
       39, 41, 43, 45, 47, 49])

In [24]:
np.eye(5)

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  1.]])